<?php

namespace Bowhead\Util\Poloniex;

class CurrencyPair
{
    const UNKNOWN = 'UNKNOWN';
    const USDT_REP = 'USDT_REP';
    const BTC_XVC = 'BTC_XVC';
    const BTC_PINK = 'BTC_PINK';
    const BTC_SYS = 'BTC_SYS';
    const BTC_EMC2 = 'BTC_EMC2';
    const BTC_RADS = 'BTC_RADS';
    const BTC_SC = 'BTC_SC';
    const BTC_MAID = 'BTC_MAID';
    const BTC_BCH = 'BTC_BCH';
    const BTC_GNT = 'BTC_GNT';
    const BTC_BCN = 'BTC_BCN';
    const BTC_REP = 'BTC_REP';
    const BTC_BCY = 'BTC_BCY';
    const BTC_GNO = 'BTC_GNO';
    const XMR_NXT = 'XMR_NXT';
    const USDT_ZEC = 'USDT_ZEC';
    const BTC_FCT = 'BTC_FCT';
    const USDT_ETH = 'USDT_ETH';
    const USDT_BTC = 'USDT_BTC';
    const BTC_LBC = 'BTC_LBC';
    const BTC_DCR = 'BTC_DCR';
    const USDT_ETC = 'USDT_ETC';
    const BTC_AMP = 'BTC_AMP';
    const BTC_XPM = 'BTC_XPM';
    const BTC_NXT = 'BTC_NXT';
    const BTC_VTC = 'BTC_VTC';
    const ETH_STEEM = 'ETH_STEEM';
    const XMR_BLK = 'XMR_BLK';
    const BTC_PASC = 'BTC_PASC';
    const XMR_ZEC = 'XMR_ZEC';
    const BTC_GRC = 'BTC_GRC';
    const BTC_NXC = 'BTC_NXC';
    const BTC_BTCD = 'BTC_BTCD';
    const BTC_LTC = 'BTC_LTC';
    const BTC_DASH = 'BTC_DASH';
    const BTC_NAUT = 'BTC_NAUT';
    const ETH_ZEC = 'ETH_ZEC';
    const BTC_ZEC = 'BTC_ZEC';
    const BTC_BURST = 'BTC_BURST';
    const BTC_BELA = 'BTC_BELA';
    const BTC_STEEM = 'BTC_STEEM';
    const BTC_ETC = 'BTC_ETC';
    const BTC_ETH = 'BTC_ETH';
    const BTC_HUC = 'BTC_HUC';
    const BTC_STRAT = 'BTC_STRAT';
    const BTC_LSK = 'BTC_LSK';
    const BTC_EXP = 'BTC_EXP';
    const BTC_CLAM = 'BTC_CLAM';
    const ETH_REP = 'ETH_REP';
    const XMR_DASH = 'XMR_DASH';
    const USDT_BCH = 'USDT_BCH';
    const USDT_DASH = 'USDT_DASH';
    const BTC_BLK = 'BTC_BLK';
    const BTC_XRP = 'BTC_XRP';
    const USDT_NXT = 'USDT_NXT';
    const BTC_NEOS = 'BTC_NEOS';
    const BTC_BTS = 'BTC_BTS';
    const BTC_DOGE = 'BTC_DOGE';
    const ETH_GNT = 'ETH_GNT';
    const BTC_SBD = 'BTC_SBD';
    const ETH_GNO = 'ETH_GNO';
    const BTC_XCP = 'BTC_XCP';
    const USDT_LTC = 'USDT_LTC';
    const BTC_BTM = 'BTC_BTM';
    const USDT_XMR = 'USDT_XMR';
    const ETH_LSK = 'ETH_LSK';
    const BTC_OMNI = 'BTC_OMNI';
    const BTC_NAV = 'BTC_NAV';
    const BTC_FLDC = 'BTC_FLDC';
    const ETH_BCH = 'ETH_BCH';
    const BTC_XBC = 'BTC_XBC';
    const BTC_DGB = 'BTC_DGB';
    const BTC_NOTE = 'BTC_NOTE';
    const XMR_BTCD = 'XMR_BTCD';
    const BTC_VRC = 'BTC_VRC';
    const BTC_RIC = 'BTC_RIC';
    const XMR_MAID = 'XMR_MAID';
    const BTC_STR = 'BTC_STR';
    const BTC_POT = 'BTC_POT';
    const BTC_XMR = 'BTC_XMR';
    const BTC_SJCX = 'BTC_SJCX';
    const BTC_VIA = 'BTC_VIA';
    const BTC_XEM = 'BTC_XEM';
    const BTC_NMC = 'BTC_NMC';
    const ETH_ETC = 'ETH_ETC';
    const XMR_LTC = 'XMR_LTC';
    const BTC_ARDR = 'BTC_ARDR';
    const BTC_FLO = 'BTC_FLO';
    const USDT_XRP = 'USDT_XRP';
    const BTC_GAME = 'BTC_GAME';
    const BTC_PPC = 'BTC_PPC';
    const XMR_BCN = 'XMR_BCN';
    const USDT_STR = 'USDT_STR';

    const ticker_id_on_instrument = [
        175 => self::USDT_REP,
        98 => self::BTC_XVC,
        73 => self::BTC_PINK,
        92 => self::BTC_SYS,
        28 => self::BTC_EMC2,
        158 => self::BTC_RADS,
        150 => self::BTC_SC,
        51 => self::BTC_MAID,
        189 => self::BTC_BCH,
        185 => self::BTC_GNT,
        7 => self::BTC_BCN,
        174 => self::BTC_REP,
        151 => self::BTC_BCY,
        187 => self::BTC_GNO,
        140 => self::XMR_NXT,
        180 => self::USDT_ZEC,
        155 => self::BTC_FCT,
        149 => self::USDT_ETH,
        121 => self::USDT_BTC,
        167 => self::BTC_LBC,
        162 => self::BTC_DCR,
        173 => self::USDT_ETC,
        160 => self::BTC_AMP,
        116 => self::BTC_XPM,
        69 => self::BTC_NXT,
        100 => self::BTC_VTC,
        169 => self::ETH_STEEM,
        130 => self::XMR_BLK,
        184 => self::BTC_PASC,
        181 => self::XMR_ZEC,
        40 => self::BTC_GRC,
        183 => self::BTC_NXC,
        12 => self::BTC_BTCD,
        50 => self::BTC_LTC,
        24 => self::BTC_DASH,
        60 => self::BTC_NAUT,
        179 => self::ETH_ZEC,
        178 => self::BTC_ZEC,
        15 => self::BTC_BURST,
        8 => self::BTC_BELA,
        168 => self::BTC_STEEM,
        171 => self::BTC_ETC,
        148 => self::BTC_ETH,
        43 => self::BTC_HUC,
        182 => self::BTC_STRAT,
        163 => self::BTC_LSK,
        153 => self::BTC_EXP,
        20 => self::BTC_CLAM,
        176 => self::ETH_REP,
        132 => self::XMR_DASH,
        191 => self::USDT_BCH,
        122 => self::USDT_DASH,
        10 => self::BTC_BLK,
        117 => self::BTC_XRP,
        124 => self::USDT_NXT,
        63 => self::BTC_NEOS,
        14 => self::BTC_BTS,
        27 => self::BTC_DOGE,
        186 => self::ETH_GNT,
        170 => self::BTC_SBD,
        188 => self::ETH_GNO,
        108 => self::BTC_XCP,
        123 => self::USDT_LTC,
        13 => self::BTC_BTM,
        126 => self::USDT_XMR,
        166 => self::ETH_LSK,
        58 => self::BTC_OMNI,
        61 => self::BTC_NAV,
        31 => self::BTC_FLDC,
        190 => self::ETH_BCH,
        104 => self::BTC_XBC,
        25 => self::BTC_DGB,
        66 => self::BTC_NOTE,
        131 => self::XMR_BTCD,
        99 => self::BTC_VRC,
        83 => self::BTC_RIC,
        138 => self::XMR_MAID,
        89 => self::BTC_STR,
        74 => self::BTC_POT,
        114 => self::BTC_XMR,
        86 => self::BTC_SJCX,
        97 => self::BTC_VIA,
        112 => self::BTC_XEM,
        64 => self::BTC_NMC,
        172 => self::ETH_ETC,
        137 => self::XMR_LTC,
        177 => self::BTC_ARDR,
        32 => self::BTC_FLO,
        127 => self::USDT_XRP,
        38 => self::BTC_GAME,
        75 => self::BTC_PPC,
        129 => self::XMR_BCN,
        125 => self::USDT_STR,
    ];

    /**
     * @param $id
     * @return mixed|string
     */
    public static function getInstrument($id)
    {
        return self::ticker_id_on_instrument[$id] ?? self::UNKNOWN;
    }
}